excel:
  file: cases.xlsx

logger:
  name: "python29"
  file: "python29log.txt"
  logger_level: "DEBUG"
  stream_level: "DEBUG"
  file_level: "INFO"

db:
  host: "120.78.128.25"
  port: 3306
  user: "future"
  password: "123456"
  charset: 'utf8'

user:
  mobile_phone: "15512345678"
  pwd: "12345678"

admin_user:
  mobile_phone: "18188889999"
  pwd: "12345678"

invest_user:
  mobile_phone: "13367899876"
  pwd: "lemonban"

host: http://api.lemonban.com/futureloan